[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Client-side routing for Next.js (this should be the only redirect for SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200